version: "3.8"

services:
  prometheus:
    image: "prom/prometheus:latest"
    hostname: "prometheus"
    restart: unless-stopped
    networks:
      - website_monitoring
    ports:
      - "127.0.0.1:9090:9090"
    user: nobody
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./config/prometheus/targets.yml:/etc/prometheus/targets.yml:ro"
      - "./config/prometheus/rules:/etc/prometheus/rules"
      - "prometheus_data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-admin-api"

  blackbox-exporter:
    image: "prom/blackbox-exporter:latest"
    hostname: "blackbox"
    restart: unless-stopped
    networks:
      - website_monitoring
    ports:
      - "127.0.0.1:9115:9115"
    volumes:
      - "./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
    command:
      - "--config.file=/etc/prometheus/blackbox-exporter.yml"

  grafana:
    image: grafana/grafana:latest
    hostname: "grafana"
    restart: unless-stopped
    networks:
      - website_monitoring
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
      # - GF_INSTALL_PLUGINS=
    volumes:
      - "./config/grafana/provisioning:/etc/grafana/provisioning"

volumes:
  prometheus_data:

networks:
  website_monitoring:
